### ISSUE TITLE
Available for consulting?

### ISSUE THREAD

**Issue by tonissimo** [inspmoore/papu#2]
Hi @inspmoore this is not the right place for this but I could not find another way to contact you. We want to use your papu project as a starting point for a new startup. Are you available to consult with us? Apologies again for posting this as an issue.

**Comment by inspmoore** [comment]
Hi @tonissimo ! You don't have to apologize. That's a very creative way to contact someone! I don't want post my email here. Do you have a website where I could find your contact info? Alternatively you can contact trough twitter @pirx__

**Comment by tonissimo** [comment]
Hello :) I tweeted at (to?) you yesterday but I don't think you saw it. My handle is antoine_______
You can shoot me an email at ab@0121.io
